version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - ./.env.local
    command: yarn run dev
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

